<header>
    <nav class="navbar">
        <div class="branding">
            <h1>AL TECHNOLOGIES</h1>
        </div>
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="jobs.php">Jobs</a></li>
            <li><a href="apply.php">Apply</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="manage.php">Manager</a></li>
            <li><a href="enhancements.php">Enhancements</a></li>
            <li><a href="enhancements2.php">Enhancement2</a></li>
            <li><a href="phpenhancements.php">EnhancementPHP</a></li>
        </ul>
    </nav>
</header>
